version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql   # <-- volume persistente
      - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  data_loader:
    build:
      context: ./mariadb_init
    depends_on:
      - mariadb
    volumes:
      - ./mariadb_init:/app
      - ./db_utils:/app/db_utils
    working_dir: /app
    command: sh -c "sleep 15 && python load_data.py"
    environment:
      - PYTHONUNBUFFERED=1