version: '2.4'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql   
      - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-prootpassword", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  data_loader:
    build:
      context: ./mariadb_init
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./mariadb_init:/app
      - ./db_utils:/app/db_utils
    working_dir: /app
    command: sh -c "python load_data.py"
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build:
      context: ./backend
    depends_on:
      - data_loader
    ports:
      - "8003:8000"
    environment:
      - PYTHONUNBUFFERED=1